---
permalink: online-help/task-specifying-the-destination-location-for-snapshot-backups.html 
sidebar: sidebar 
keywords:  
summary: È possibile configurare la posizione di destinazione per i backup Snapshot di Unified Manager su un volume già configurato in uno dei cluster ONTAP. La posizione viene definita dalla console di manutenzione di Unified Manager. 
---
= Specifica del percorso di destinazione per i backup Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare la posizione di destinazione per i backup Snapshot di Unified Manager su un volume già configurato in uno dei cluster ONTAP. La posizione viene definita dalla console di manutenzione di Unified Manager.



== Prima di iniziare

* È necessario disporre delle credenziali dell'utente root per l'host Linux su cui è installato Unified Manager.
* Per accedere alla console di manutenzione del server Unified Manager, è necessario disporre di un ID utente e di una password autorizzati.
* È necessario disporre dell'indirizzo IP di Cluster Management, del nome della VM di storage, del nome del volume e del nome utente e della password del sistema di storage.
* È necessario aver montato il volume sull'host di Unified Manager e disporre del percorso di montaggio.




== Fasi

. Utilizzando Secure Shell, connettersi all'indirizzo IP o al nome di dominio completo del sistema Unified Manager.
. Accedere al sistema con il nome utente di manutenzione (umadmin) e la password.
. Immettere il comando `maintenance_console` E premere Invio.
. Nella console di manutenzione *Menu principale*, inserire il numero dell'opzione *Backup Restore*.
. Inserire il numero per *Configure NetApp Snapshot Backup*.
. Inserire il numero di *Configuration for NFS*.
. Esaminare le informazioni da fornire, quindi inserire il numero *Enter Backup Configuration Details* (Immetti dettagli configurazione backup).
. Per identificare il volume in cui verrà scritta l'istantanea, inserire l'indirizzo IP dell'interfaccia di gestione del cluster, il nome della VM di storage, il nome del volume, il nome utente e la password del sistema di storage e il percorso di montaggio.
. Verificare queste informazioni e immettere `y`.
+
Il sistema esegue le seguenti operazioni:

+
** Stabilisce la connessione al cluster
** Interrompe tutti i servizi
** Crea una nuova directory nel volume e copia i file di configurazione del database di Unified Manager
** Elimina i file da Unified Manager e crea un collegamento simbolico alla nuova directory del database
** Riavvia tutti i servizi


. Uscire dalla console di manutenzione e avviare l'interfaccia di Unified Manager per creare la pianificazione di backup di Snapshot, se non è già stata eseguita questa operazione.

