---
permalink: online-help/task-enabling-and-disabling-the-ability-to-upload-scripts.html 
sidebar: sidebar 
keywords: script upload 
summary: 'Per impostazione predefinita, è attivata la possibilità di caricare gli script in Unified Manager ed eseguirli. Se l"organizzazione non desidera consentire questa attività per motivi di sicurezza, è possibile disattivare questa funzionalità.' 
---
= Abilitazione e disabilitazione della capacità di caricare gli script
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per impostazione predefinita, è attivata la possibilità di caricare gli script in Unified Manager ed eseguirli. Se l'organizzazione non desidera consentire questa attività per motivi di sicurezza, è possibile disattivare questa funzionalità.



== Prima di iniziare

È necessario disporre del ruolo di amministratore dell'applicazione.



== Fasi

. Nel riquadro di navigazione a sinistra, fare clic su *Generale* > *Impostazioni funzionalità*.
. Nella pagina *Impostazioni funzionalità*, disattivare o attivare lo scripting scegliendo una delle seguenti opzioni:
+
|===
| Se si desidera... | Quindi... 


 a| 
Disattivare gli script
 a| 
Nel pannello *script Upload*, spostare il cursore verso sinistra.



 a| 
Abilitare gli script
 a| 
Nel pannello *script Upload*, spostare il cursore verso destra.

|===

