---
permalink: reporting/concept-unified-manager-reporting.html 
sidebar: sidebar 
keywords:  
summary: 'Active IQ Unified Manager (precedentemente noto come Gestore unificato di OnCommand) consente di visualizzare, personalizzare, scaricare e pianificare report per i sistemi storage ONTAP. I report possono fornire dettagli sulla capacità, lo stato di salute, le performance e le relazioni di protezione del sistema di storage.' 
---
= Reporting di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager (in precedenza Unified Manager di OnCommand) consente di visualizzare, personalizzare, scaricare e pianificare report per i sistemi storage ONTAP. I report possono fornire dettagli sulla capacità, lo stato di salute, le performance e le relazioni di protezione del sistema di storage.

La nuova funzionalità di reporting e scheduling di Unified Manager introdotta in Active IQ Unified Manager 9.6 sostituisce il precedente motore di reporting che era stato ritirato nella versione 9.5 di Unified Manager.

Il reporting offre diverse viste della rete, offrendo informazioni pratiche su capacità, stato di salute, performance e dati di protezione. È possibile personalizzare le visualizzazioni visualizzando, nascondendo e riordinando le colonne, filtrando i dati, ordinando i dati, e la ricerca dei risultati. È possibile salvare visualizzazioni personalizzate per il riutilizzo, scaricarle come report e pianificarle come report ricorrenti da distribuire tramite e-mail.

A partire da Active IQ Unified Manager 9.8, è possibile scaricare le viste in formato Microsoft® Excel e personalizzarle. È possibile utilizzare funzionalità avanzate di Excel, come ordinamento complesso, filtri a più livelli, tabelle pivot e grafici. Una volta soddisfatto del report Excel risultante, è possibile caricare il file Excel per utilizzarlo ogni volta che il report viene pianificato e condiviso.
