---
permalink: data-protection/reference-relationship-last-1-month-transfer-rate-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vista Relationship: Last 1 Month Transfer Rate consente di analizzare la quantità di volume di dati che viene trasferita giorno per giorno per i volumi in relazioni asincrone. Questa pagina fornisce inoltre informazioni dettagliate sui trasferimenti di volumi giornalieri e sul tempo necessario per completare l"operazione di trasferimento.' 
---
= Relazione: Vista tasso di trasferimento dell'ultimo mese
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista Relationship: Last 1 Month Transfer Rate consente di analizzare la quantità di volume di dati che viene trasferita giorno per giorno per i volumi in relazioni asincrone. Questa pagina fornisce inoltre informazioni dettagliate sui trasferimenti di volumi giornalieri e sul tempo necessario per completare l'operazione di trasferimento.

I controlli nella parte superiore della pagina consentono di selezionare una vista particolare (per lo stato, le prestazioni, la capacità e così via), eseguire ricerche per individuare oggetti specifici, creare e applicare filtri per restringere l'elenco dei dati visualizzati, aggiungere/rimuovere/riordinare le colonne della pagina, ed esportare i dati della pagina in un `.csv`, `.pdf`, o. `.xlsx` file. Dopo aver personalizzato la pagina, è possibile salvare i risultati come vista personalizzata e pianificare un report dei dati da generare e inviare via email a intervalli regolari.

* *Dimensione trasferimento totale*
+
Visualizza le dimensioni totali del trasferimento del volume in gigabyte.

* *Giorno*
+
Visualizza il giorno in cui è stato avviato il trasferimento del volume.

* *Ora di fine*
+
Visualizza l'ora di fine del trasferimento del volume con la data.


