---
permalink: data-protection/reference-relationship-last-1-month-transfer-status-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vista Relationship: Last 1 Month Transfer Status (relazione: Stato trasferimento ultimo 1 mese) consente di analizzare i trend di trasferimento dei volumi in un determinato periodo di tempo per i volumi in relazioni asincrone. Questa pagina visualizza anche se il trasferimento del volume è stato un successo o un errore.' 
---
= Relazione: Vista Stato trasferimento ultimo 1 mese
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vista Relationship: Last 1 Month Transfer Status (relazione: Stato trasferimento ultimo 1 mese) consente di analizzare i trend di trasferimento dei volumi in un determinato periodo di tempo per i volumi in relazioni asincrone. Questa pagina visualizza anche se il trasferimento del volume è stato un successo o un errore.

I controlli nella parte superiore della pagina consentono di selezionare una vista particolare (per lo stato, le prestazioni, la capacità e così via), eseguire ricerche per individuare oggetti specifici, creare e applicare filtri per restringere l'elenco dei dati visualizzati, aggiungere/rimuovere/riordinare le colonne della pagina, ed esportare i dati della pagina in un `.csv`, `.pdf`, o. `.xlsx` file. Dopo aver personalizzato la pagina, è possibile salvare i risultati come vista personalizzata e pianificare un report dei dati da generare e inviare via email a intervalli regolari.

* *Volume di origine*
+
Visualizza il nome del volume di origine.

* *Volume di destinazione*
+
Visualizza il nome del volume di destinazione.

* *Tipo di operazione*
+
Visualizza il tipo di trasferimento del volume.

* *Risultato dell'operazione*
+
Visualizza se il trasferimento del volume è stato eseguito correttamente.

* *Ora di inizio trasferimento*
+
Visualizza l'ora di inizio del trasferimento del volume.

* *Ora di fine trasferimento*
+
Visualizza l'ora di fine del trasferimento del volume.

* *Durata trasferimento*
+
Visualizza il tempo impiegato (in ore) per completare il trasferimento del volume.

* *Dimensione trasferimento*
+
Visualizza le dimensioni (in MB) del volume trasferito.

* *SVM di origine*
+
Visualizza il nome della SVM (Storage Virtual Machine).

* *Cluster di origine*
+
Visualizza il nome del cluster di origine.

* *SVM di destinazione*
+
Visualizza il nome SVM di destinazione.

* *Cluster di destinazione*
+
Visualizza il nome del cluster di destinazione.


